version: '3.8'

services:
  backend:
    build:
      context: ./src
      dockerfile: CongestionTaxCalculator.Web/Dockerfile
    container_name: backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:CongestionTaxCalculatorConnection=mongodb://root:root@mongodb:27017/CongestionTaxCalculator?authSource=admin"
    ports:
      - '8000:80'
    depends_on:
      - mongodb

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    command: mongod --quiet --logpath /dev/null
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - mongodb-volume:/data/db
    ports:
      - 27017:27017

volumes:
  mongodb-volume: